### ISSUE TITLE
Improve Documentation please

### ISSUE THREAD

**Issue by Lauro235** [skills/test-with-actions#32]
As far as I can tell, the documentation for the test-with-actions lesson template is very out of date.

The steps from 8 - 10 cannot be followed. The language doesn't match what is actually seen on the screen. Not only that but no prompt is given to create a new branch or `Create a pull request`.

Perhaps I'm just misunderstanding the instructions but regardless, despite my best faith attempt at following the lesson, I cannot seem to make sense of the instructions as listed below.

8. Click Start commit, and choose to make a new branch named ci.
9. Click Propose a new file.
10. Click Create pull request.

**Comment by cmwilson21** [comment]
@Lauro235 Thanks for opening an issue. We are currently updating the Skills courses, I'll go ahead and triage this for review.

**Comment by Lauro235** [comment]
Looking back I can see my 'issue' may not be helpful to everyone, but I broadly I feel that the more accurate the instructions, the less the user has to worry about learning the GUI interface and the more they can focus on the content of Github actions. I appreciate the response and the updating of documentation.

**Comment by cmwilson21** [comment]
@m-den-01A Thank you for the suggestions! I can confirm that screenshots will be updated as we roll through updating the courses in general. We appreciate your suggestions on the matter!

@Lauro235 Feedback is always helpful! Thank you again for sharing with us.

**Comment by kcjonesevans** [comment]
@cmwilson21 do you have a solution for how to get the step 1 action to move on to step 2? I someone has no experience with actions they will not know how to inspect the actions in place to get them to pass and move on to the next step making this course unusable.

**Comment by sinsukehlab** [comment]
Resolved in #51

**Comment by hectorsector** [comment]
Thanks for the very helpful feedback, folks. I think this course has gotten some improvements since it was opened and, although still not perfect, the feedback in this issue may be outdated now.
